version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: messaging_user
      MYSQL_DATABASE: messaging_db
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_USER: messaging_user
      MYSQL_DATABASE: messaging_db
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_root_password

volumes:
  db_data:
